apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: postgresql-auth
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: cluster/postgresql
        property: superuser_password
    - secretKey: GRAFANA_PASSWORD
      remoteRef:
        key: cluster/grafana
        property: db_password
    - secretKey: DTRACK_PASSWORD
      remoteRef:
        key: cluster/dtrack
        property: db_password
