apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-homelab
    kind: ClusterSecretStore
  target:
    name: postgresql-auth
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgres-superuser-password
    - secretKey: GRAFANA_PASSWORD
      remoteRef:
        key: grafana-db-password
    - secretKey: DTRACK_PASSWORD
      remoteRef:
        key: dtrack-db-password
