apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap-postgresql.yaml
  - externalsecret-postgresql.yaml
  - service.yaml
  - statefulset.yaml

labels:
  - pairs:
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: data
      app.kubernetes.io/managed-by: argocd
    includeSelectors: false
    includeTemplates: true
