apiVersion: v1
kind: Secret
metadata:
  name: postgresql-auth
  labels:
    app.kubernetes.io/name: postgresql
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: change-me
  POSTGRES_DB: app
