apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgresql
  labels:
    app.kubernetes.io/name: postgresql
    # release=monitoring e o serviceMonitorSelector do kube-prometheus-stack.
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
